// capitals.js
export const wordEmojiPairs = [
    { match: "københavn", emoji: "https://flagcdn.com/w80/dk.png" },
    { match: "stockholm", emoji: "https://flagcdn.com/w80/se.png" },
    { match: "oslo", emoji: "https://flagcdn.com/w80/no.png" },
    { match: "berlin", emoji: "https://flagcdn.com/w80/de.png" },
    { match: "paris", emoji: "https://flagcdn.com/w80/fr.png" },
    { match: "rom", emoji: "https://flagcdn.com/w80/it.png" },
    { match: "madrid", emoji: "https://flagcdn.com/w80/es.png" },
    { match: "athen", emoji: "https://flagcdn.com/w80/gr.png" },
    { match: "helsinki", emoji: "https://flagcdn.com/w80/fi.png" },
    { match: "london", emoji: "https://flagcdn.com/w80/gb.png" },
    { match: "dublin", emoji: "https://flagcdn.com/w80/ie.png" },
    { match: "lisabon", emoji: "https://flagcdn.com/w80/pt.png" },
    { match: "amsterdam", emoji: "https://flagcdn.com/w80/nl.png" },
    { match: "bruxelles", emoji: "https://flagcdn.com/w80/be.png" },
    { match: "warszawa", emoji: "https://flagcdn.com/w80/pl.png" },
    { match: "wien", emoji: "https://flagcdn.com/w80/at.png" },
    { match: "bern", emoji: "https://flagcdn.com/w80/ch.png" },
    { match: "prag", emoji: "https://flagcdn.com/w80/cz.png" },
    { match: "budapest", emoji: "https://flagcdn.com/w80/hu.png" },
    { match: "bukarest", emoji: "https://flagcdn.com/w80/ro.png" },
    { match: "sofia", emoji: "https://flagcdn.com/w80/bg.png" },
    { match: "zagreb", emoji: "https://flagcdn.com/w80/hr.png" },
    { match: "beograd", emoji: "https://flagcdn.com/w80/rs.png" },
    { match: "sarajevo", emoji: "https://flagcdn.com/w80/ba.png" },
    { match: "bratislava", emoji: "https://flagcdn.com/w80/sk.png" },
    { match: "ljubljana", emoji: "https://flagcdn.com/w80/si.png" },
    { match: "vilnius", emoji: "https://flagcdn.com/w80/lt.png" },
    { match: "riga", emoji: "https://flagcdn.com/w80/lv.png" },
    { match: "tallinn", emoji: "https://flagcdn.com/w80/ee.png" },
    { match: "kyiv", emoji: "https://flagcdn.com/w80/ua.png" },
    { match: "minsk", emoji: "https://flagcdn.com/w80/by.png" },
    { match: "moskva", emoji: "https://flagcdn.com/w80/ru.png" },
    { match: "ankara", emoji: "https://flagcdn.com/w80/tr.png" },
    { match: "nikosia", emoji: "https://flagcdn.com/w80/cy.png" },
    { match: "tbilisi", emoji: "https://flagcdn.com/w80/ge.png" },
    { match: "erevan", emoji: "https://flagcdn.com/w80/am.png" },
    { match: "washington", emoji: "https://flagcdn.com/w80/us.png" },
    { match: "ottawa", emoji: "https://flagcdn.com/w80/ca.png" },
    { match: "mexico city", emoji: "https://flagcdn.com/w80/mx.png" },
    { match: "brasilia", emoji: "https://flagcdn.com/w80/br.png" },
    { match: "buenos aires", emoji: "https://flagcdn.com/w80/ar.png" },
    { match: "santiago", emoji: "https://flagcdn.com/w80/cl.png" },
    { match: "lima", emoji: "https://flagcdn.com/w80/pe.png" },
    { match: "beijing", emoji: "https://flagcdn.com/w80/cn.png" },
    { match: "tokyo", emoji: "https://flagcdn.com/w80/jp.png" },
    { match: "new delhi", emoji: "https://flagcdn.com/w80/in.png" },
    { match: "islamabad", emoji: "https://flagcdn.com/w80/pk.png" },
    { match: "canberra", emoji: "https://flagcdn.com/w80/au.png" }
  ];
  