// fartoejer.js
export const wordEmojiPairs = [
    { match: "luftballon", emoji: "🎈" },
    { match: "cykel", emoji: "🚲" },
    { match: "lastbil", emoji: "🚛" },
    { match: "scooter", emoji: "🛵" },
    { match: "bus", emoji: "🚌" },
    { match: "traktor", emoji: "🚜" },
    { match: "helikopter", emoji: "🚁" },
  
    // More to complete 50:
    { match: "tog", emoji: "🚆" },
    { match: "metro", emoji: "🚇" },
    { match: "sporvogn", emoji: "🚋" },
    { match: "bil", emoji: "🚗" },
    { match: "taxa", emoji: "🚕" },
    { match: "politibil", emoji: "🚓" },
    { match: "brandbil", emoji: "🚒" },
    { match: "ambulance", emoji: "🚑" },
    { match: "motorcykel", emoji: "🏍️" },
    { match: "skateboard", emoji: "🛹" },
    { match: "rulleskøjter", emoji: "🛼" },
    { match: "el-løbehjul", emoji: "🛴" },
    { match: "varevogn", emoji: "🚐" },
    { match: "minibus", emoji: "🚐" },
    { match: "båd", emoji: "🚤" },
    { match: "færge", emoji: "⛴️" },
    { match: "sejlbåd", emoji: "⛵" },
    { match: "kano", emoji: "🛶" },
    { match: "yacht", emoji: "🛥️" },
    { match: "passagerfly", emoji: "✈️" },
    { match: "rumskib", emoji: "🚀" },
    { match: "raket", emoji: "🚀" },
    { match: "trolleybus", emoji: "🚎" },
    { match: "monorail", emoji: "🚝" },
    { match: "sporvogn", emoji: "🚋" },
    { match: "veteranbil", emoji: "🚘" },
    { match: "sportsvogn", emoji: "🏎️" },
    { match: "tank", emoji: "🚓" },
    { match: "gokart", emoji: "🏎️" },
    { match: "campingvogn", emoji: "🚐" },
    { match: "pickup", emoji: "🛻" },
    { match: "truck", emoji: "🚚" },
    { match: "arbejdskøretøj", emoji: "🚜" },
    { match: "gummiged", emoji: "🚧" },
    { match: "elbil", emoji: "🔋" },
    { match: "dieselbil", emoji: "🛢️" },
    { match: "svævebane", emoji: "🚡" },
    { match: "kabelvogn", emoji: "🚠" },
    { match: "ballonfly", emoji: "🎈" },
    { match: "kørestol", emoji: "♿" },
    { match: "hestevogn", emoji: "🐴" },
    { match: "slæde", emoji: "🛷" }
  ];
  