// frugtGrønt.js  
export const wordEmojiPairs = [
    { match: "banan", emoji: "🍌" },
    { match: "æble", emoji: "🍎" },
    { match: "kiwi", emoji: "🥝" },
    { match: "vindrue", emoji: "🍇" },
    { match: "bladselleri", emoji: "🥬" },
    { match: "aubergine", emoji: "🍆" },
    { match: "blomkål", emoji: "🥦" },
    { match: "gulerod", emoji: "🥕" },
    { match: "radiser", emoji: "❤️‍🩹" },
    { match: "broccoli", emoji: "🥦" },
    { match: "græskar", emoji: "🎃" },
    { match: "tomat", emoji: "🍅" },
    { match: "appelsin", emoji: "🍊" },
    { match: "citron", emoji: "🍋" },
    { match: "lime", emoji: "🟢" },
    { match: "vandmelon", emoji: "🍉" },
    { match: "jordbær", emoji: "🍓" },
    { match: "hindbær", emoji: "🫐" },
    { match: "blåbær", emoji: "🔵" },
    { match: "pære", emoji: "🍐" },
    { match: "fersken", emoji: "🍑" },
    { match: "ananas", emoji: "🍍" },
    { match: "kokosnød", emoji: "🥥" },
    { match: "salat", emoji: "🥗" },
    { match: "agurk", emoji: "🥒" },
    { match: "peberfrugt", emoji: "🫑" },
    { match: "løg", emoji: "🧅" },
    { match: "hvidløg", emoji: "🧄" },
    { match: "majs", emoji: "🌽" },
    { match: "svamp", emoji: "🍄" },
    { match: "ærter", emoji: "🟢" },
    { match: "bønner", emoji: "🫘" },
    { match: "spinat", emoji: "🥬" },
    { match: "rødbede", emoji: "🟣" },
    { match: "grøntsager", emoji: "🥦" },
    { match: "frugt", emoji: "🍎" },
    { match: "melon", emoji: "🍈" },
    { match: "dadler", emoji: "🟤" },
    { match: "tranebær", emoji: "🟥" },
    { match: "figner", emoji: "🟣" },
    { match: "granatæble", emoji: "🔴" },
    { match: "papaya", emoji: "🟠" },
    { match: "passionsfrugt", emoji: "🟡" },
    { match: "kål", emoji: "🥬" },
    { match: "romainesalat", emoji: "🥬" },
    { match: "koriander", emoji: "🌿" },
    { match: "basilikum", emoji: "🌿" },
    { match: "ingefær", emoji: "🟤" },
    { match: "dild", emoji: "🌿" }
  ];
  