// household.js
export const wordEmojiPairs = [
  { match: "stol", emoji: "🪑" },
  { match: "spejl", emoji: "🪞" },
  { match: "seng", emoji: "🛏️" },
  { match: "lampe", emoji: "💡" },
  { match: "toilet", emoji: "🚽" },
  { match: "badekar", emoji: "🛁" },
  { match: "bruser", emoji: "🚿" },
  { match: "bord", emoji: "🪟" }, // window used as visual table stand-in
  { match: "dør", emoji: "🚪" },
  { match: "bog", emoji: "📘" },
  { match: "fjernsyn", emoji: "📺" },
  { match: "telefon", emoji: "📱" },
  { match: "computer", emoji: "💻" },
  { match: "vaskemaskine", emoji: "🧺" },
  { match: "strygjern", emoji: "🧼" },
  { match: "køleskab", emoji: "🧊" },
  { match: "ovn", emoji: "🔥" },
  { match: "komfur", emoji: "🍳" },
  { match: "gryde", emoji: "🥘" },
  { match: "pande", emoji: "🍳" },
  { match: "kop", emoji: "☕" },
  { match: "glas", emoji: "🥛" },
  { match: "tallerken", emoji: "🍽️" },
  { match: "ske", emoji: "🥄" },
  { match: "gaffel", emoji: "🍴" },
  { match: "kniv", emoji: "🔪" },
  { match: "køkken", emoji: "🍽️" },
  { match: "badeværelse", emoji: "🛁" },
  { match: "soveværelse", emoji: "🛏️" },
  { match: "stue", emoji: "🛋️" },
  { match: "kontor", emoji: "🖥️" },
  { match: "gardin", emoji: "🪟" },
  { match: "pude", emoji: "🛏️" },
  { match: "tæppe", emoji: "🧶" },
  { match: "skab", emoji: "🗄️" },
  { match: "hylde", emoji: "📚" },
  { match: "billede", emoji: "🖼️" },
  { match: "ur", emoji: "⏰" },
  { match: "vækkeur", emoji: "⏱️" },
  { match: "ventilator", emoji: "🌀" },
  { match: "lys", emoji: "💡" },
  { match: "skraldespand", emoji: "🗑️" },
  { match: "dørmåtte", emoji: "🧽" },
  { match: "kost", emoji: "🧹" },
  { match: "støvsuger", emoji: "🧼" },
  { match: "håndklæde", emoji: "🧻" },
  { match: "toiletpapir", emoji: "🧻" },
  { match: "sæbe", emoji: "🧼" },
  { match: "toothbrush", emoji: "🪥" },
  { match: "tandpasta", emoji: "🪥" },
];


// Let me know if you want these broken down by room later, or themed as “Kitchen only,” “Bathroom only,” etc.