// legeplads.js
export const wordEmojiPairs = [
    { match: "gynge", emoji: "🎠" },
    { match: "rutchebane", emoji: "🎢" },
    { match: "vippe", emoji: "↕️" },
    { match: "sandkasse", emoji: "🏖️" },
    { match: "klatrestativ", emoji: "🧗" },
    { match: "trampolin", emoji: "🤸" },
    { match: "balanceringsbjælke", emoji: "➖" },
    { match: "legehus", emoji: "🏡" },
    { match: "bold", emoji: "⚽" },
    { match: "fodboldmål", emoji: "🥅" },
    { match: "basketkurv", emoji: "🏀" },
    { match: "hoppedyr", emoji: "🦘" },
    { match: "cykel", emoji: "🚲" },
    { match: "løbehjul", emoji: "🛴" },
    { match: "rulleskøjter", emoji: "🛼" },
    { match: "karrusel", emoji: "🎡" },
    { match: "snurretop", emoji: "🌀" },
    { match: "sjippetov", emoji: "➰" },
    { match: "ballon", emoji: "🎈" },
    { match: "såpebobler", emoji: "🫧" },
    { match: "bamse", emoji: "🧸" },
    { match: "dukke", emoji: "🪆" },
    { match: "legoklodser", emoji: "🧱" },
    { match: "vandpistol", emoji: "🔫" },
    { match: "hinkesten", emoji: "🪨" },
    { match: "gyngedyr", emoji: "🐴" },
    { match: "legeplads", emoji: "🏞️" },
    { match: "perleplade", emoji: "🧿" },
    { match: "skovl", emoji: "🛠️" },
    { match: "spand", emoji: "🪣" },
    { match: "græs", emoji: "🌱" },
    { match: "bænk", emoji: "🪑" },
    { match: "madpakke", emoji: "🥪" },
    { match: "drikkedunk", emoji: "🥤" },
    { match: "solhat", emoji: "👒" },
    { match: "solcreme", emoji: "🧴" },
    { match: "sko", emoji: "👟" },
    { match: "jakke", emoji: "🧥" },
    { match: "legekammerat", emoji: "🧒" },
    { match: "voksen", emoji: "🧑" },
    { match: "træ", emoji: "🌳" },
    { match: "fugl", emoji: "🐦" },
    { match: "myg", emoji: "🦟" },
    { match: "sol", emoji: "☀️" },
    { match: "skygge", emoji: "🌤️" },
    { match: "måne", emoji: "🌙" },
    { match: "regn", emoji: "🌧️" },
    { match: "regnbue", emoji: "🌈" },
    { match: "vind", emoji: "💨" }
  ];
  