// spisetid.js or mad.js
export const wordEmojiPairs = [
    { match: "tallerken", emoji: "🍽️" },
    { match: "gafler", emoji: "🍴" },
    { match: "kniv", emoji: "🔪" },
    { match: "grydelap", emoji: "🧤" },
    { match: "tekande", emoji: "🫖" },
    { match: "ris", emoji: "🍚" },
    { match: "laks", emoji: "🐟" },
    { match: "is", emoji: "🍨" },
    { match: "salt", emoji: "🧂" },
    { match: "peber", emoji: "🧂" },
    { match: "ost", emoji: "🧀" },
    { match: "chokolade", emoji: "🍫" },
    { match: "kop", emoji: "☕" },
    { match: "glas", emoji: "🥛" },
    { match: "kaffe", emoji: "☕" },
    { match: "te", emoji: "🍵" },
    { match: "sukker", emoji: "🍬" },
    { match: "brød", emoji: "🍞" },
    { match: "smør", emoji: "🧈" },
    { match: "æg", emoji: "🥚" },
    { match: "bacon", emoji: "🥓" },
    { match: "pølse", emoji: "🌭" },
    { match: "pizza", emoji: "🍕" },
    { match: "burger", emoji: "🍔" },
    { match: "sandwich", emoji: "🥪" },
    { match: "salat", emoji: "🥗" },
    { match: "grøntsager", emoji: "🥦" },
    { match: "gulerod", emoji: "🥕" },
    { match: "tomat", emoji: "🍅" },
    { match: "agurk", emoji: "🥒" },
    { match: "kartoffel", emoji: "🥔" },
    { match: "kød", emoji: "🥩" },
    { match: "kylling", emoji: "🍗" },
    { match: "fisk", emoji: "🐠" },
    { match: "vand", emoji: "💧" },
    { match: "juice", emoji: "🧃" },
    { match: "mælk", emoji: "🥛" },
    { match: "sodavand", emoji: "🥤" },
    { match: "isvaffel", emoji: "🍦" },
    { match: "kage", emoji: "🍰" },
    { match: "boller", emoji: "🥯" },
    { match: "marmelade", emoji: "🥫" },
    { match: "yoghurt", emoji: "🥣" },
    { match: "pasta", emoji: "🍝" },
    { match: "suppe", emoji: "🥣" },
    { match: "gryderet", emoji: "🍲" },
    { match: "vaffel", emoji: "🧇" },
    { match: "honning", emoji: "🍯" },
    { match: "sirup", emoji: "🍯" }
  ];
  