// transport.js
export const wordEmojiPairs = [
  { match: "bil", emoji: "🚗" },
  { match: "tog", emoji: "🚆" },
  { match: "bus", emoji: "🚌" },
  { match: "cykel", emoji: "🚲" },
  { match: "motorcykel", emoji: "🏍️" },
  { match: "fly", emoji: "✈️" },
  { match: "helikopter", emoji: "🚁" },
  { match: "skib", emoji: "🚢" },
  { match: "båd", emoji: "🛥️" },
  { match: "færge", emoji: "⛴️" },
  { match: "lastbil", emoji: "🚚" },
  { match: "varevogn", emoji: "🚐" },
  { match: "trailer", emoji: "🚛" },
  { match: "sporvogn", emoji: "🚋" },
  { match: "metro", emoji: "🚇" },
  { match: "taxa", emoji: "🚕" },
  { match: "ambulance", emoji: "🚑" },
  { match: "brandbil", emoji: "🚒" },
  { match: "politi", emoji: "🚓" },
  { match: "campingvogn", emoji: "🏕️" },
  { match: "rulleskøjter", emoji: "🛼" },
  { match: "løbehjul", emoji: "🛴" },
  { match: "traktor", emoji: "🚜" },
  { match: "monorail", emoji: "🚝" },
  { match: "bjergbane", emoji: "🚞" },
  { match: "lufthavn", emoji: "🛫" },
  { match: "togstation", emoji: "🚉" },
  { match: "parkeringsplads", emoji: "🅿️" },
  { match: "vej", emoji: "🛣️" },
  { match: "motorvej", emoji: "🛤️" },
  { match: "rundkørsel", emoji: "⭕" },
  { match: "tankstation", emoji: "⛽" },
  { match: "trafiklys", emoji: "🚦" },
  { match: "fodgængerfelt", emoji: "🚸" },
  { match: "bro", emoji: "🌉" },
  { match: "tunnel", emoji: "🚇" },
  { match: "garage", emoji: "🏠" },
  { match: "hjul", emoji: "🛞" },
  { match: "rat", emoji: "🛞" },
  { match: "bremse", emoji: "🛑" },
  { match: "nummerplade", emoji: "🔢" },
  { match: "sikkerhedssele", emoji: "🎗️" },
  { match: "bagagerum", emoji: "📦" },
  { match: "kontroltårn", emoji: "🗼" },
  { match: "navigationssystem", emoji: "🧭" },
  { match: "fartpilot", emoji: "🌀" },
  { match: "chauffør", emoji: "🧑‍✈️" },
  { match: "passager", emoji: "🧍" },
  { match: "billede", emoji: "🎫" },
  { match: "rute", emoji: "📍" }
];


// Let me know if you'd like separate themes later like "public transport," "road vehicles," or "airport stuff." 🚦🛣️✈️